stages:
  - build

frontend:
  stage: build
  image: node:14
  before_script:
    - cd frontend
    - npm install -g npm@7.9.0
    - npm install -g @angular/cli
    - npm ci
  script:
    - ng build --prod
  cache:
    key: frontend
    paths:
      - frontend/node_modules/

backend:
  stage: build
  image: node:14
  before_script:
    - cd backend
    - npm ci
  script:
    - npm run build
  cache:
    key: backend
    paths:
      - backend/node_modules/